name: Conventional Commits Checking
description: "Validates that a pull request title is compatible with Conventional Commits."
runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      with:
        script: |
          const validator = /^(chore|feat|fix|revert|docs|style)(\((((CCIE|CDI|PRODSEC|SECENG|ONCALL)-[0-9]+)|([a-z-]+))\))?(!)?: (.)+$/
          const title = context.payload.pull_request.title
          const is_valid = validator.test(title)

          if (!is_valid) {
            const regex = validator.toString()
            core.setFailed(`Your pr title doesn't adhere to conventional commits syntax. Start with chore, feat, fix, revert, or docs and add an ! if the change is breaking. Title must satisfy this regex: ${regex}.`)
          }
# bump
