name: Conventional Commits Checking
description: "Validates that a pull request title is compatible with Conventional Commits."
inputs:
  extra-jira-projects:
    description: "Comma-separated list of additional JIRA project prefixes to allow in scopes (e.g. 'INFRA,PLAT')."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      with:
        script: |
          // https://www.conventionalcommits.org/en/v1.0.0/
          const types = [
            'build',
            'chore',
            'ci',
            'deps',
            'docs',
            'feat',
            'fix',
            'perf',
            'refactor',
            'revert',
            'style',
            'test',
          ]
          const jiraProjects = [
            'CCIE',
            'CDI',
            'ONCALL',
            'PRODSEC',
            'SECENG',
          ]

          const extra = `${{ inputs.extra-jira-projects }}`
            .split(',')
            .map(s => s.trim())
            .filter(Boolean)
          jiraProjects.push(...extra)

          const typePattern = types.join('|')
          const scopePattern = `(\\(((?:${jiraProjects.join('|')})-[0-9]+|[a-z][a-z0-9-]*)\\))`
          const validator = new RegExp(`^(${typePattern})${scopePattern}?(!)?: .+$`)

          const title = context.payload.pull_request.title
          if (!validator.test(title)) {
            core.setFailed(
              `PR title doesn't follow conventional commits.\n` +
              `Expected format: <type>(<optional scope>): <description>\n` +
              `Valid types: ${types.join(', ')}\n` +
              `Example: feat(auth): add SSO login support`
            )
          }
