# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "looker" {
  source           = "git@github.com:chanzuckerberg/shared-infra//terraform/modules/looker?ref=looker-v1.3.2"
  cloud_env        = local.cloud_env
  eks_cluster_name = local.eks_cluster_name
  eks_env          = local.eks_env
  kubeconfig       = local.kubeconfig
  looker_fqdn      = local.looker_fqdn
  looker_image     = local.looker_image
  looker_image_tag = local.looker_image_tag
  looker_version   = local.looker_version
  namespace        = local.namespace
  replica_count    = local.replica_count
  route53_zone_id  = local.route53_zone_id
  tags             = local.tags

}
