name: Create or Update a Happy Stack
description: "Will create or update a Happy Stack"
inputs:
  stack-name:
    description: "Name of the stack to create or update"
    required: true
  create-tag:
    description: "Should we build and tag docker images. Defaults to false and assumes images already exist."
    default: "false"
    required: false
  tfe-token:
    description: "TFE Token"
    required: true
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "0.15.3"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/.github/actions/install-happy@install-happy-v1.3.0
      with:
        happy_version: ${{ inputs.happy_version }}
    - name: Create or update happy stack
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
        STACK_NAME: ${{ inputs.stack-name }}
        CREATE_TAG: ${{ inputs.create-tag }}
      shell: bash
      run: |
        set -ue
        set -o pipefail

        echo "Targetting Stack ${STACK_NAME}"

        if $(happy list --aws-profile "" 2>&1 | grep -q ${STACK_NAME} ); then
          echo "Updating stack ${STACK_NAME}"
          happy update --aws-profile "" --create-tag=${CREATE_TAG} --tag sha-${GITHUB_SHA} ${STACK_NAME}
        else
          echo "Creating stack ${STACK_NAME}"
          happy create --aws-profile "" --create-tag=${CREATE_TAG} --tag sha-${GITHUB_SHA} ${STACK_NAME}
        fi
