name: Create or Update a Happy Stack
description: "Will create or update a Happy Stack"
inputs:
  tfe-token:
    description: "TFE Token"
    required: true
  stack-name:
    description: "Name of the stack to create or update"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/.github/actions/install-happy@53ae13476bb464534ba471b07f4a3b3eb2d11e30
    - name: Create or update happy stack
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
        STACK_NAME: ${{ inputs.stack-name }}
      shell: bash
      run: |
        set -e
        set -o pipefail
        AWS_PROFILE=""

        if $(happy list | grep -q ${STACK_NAME}} ); then
          echo "Updating stack ${STACK_NAME}"
          happy update --tag sha-${GITHUB_SHA} ${STACK_NAME}
        else
          echo "Creating stack ${STACK_NAME}"
          happy create  --tag sha-${GITHUB_SHA} ${STACK_NAME}
        fi

# context.payload.pull_request.base.ref
# context.payload.pull_request.head.ref
