name: Create or Update a Happy Stack
description: "Will create, update, or delete a Happy Stack"
inputs:
  operation:
    description: "Operation we want this to perform. If not provided, happy will automatically create or update the stack with given name. Could be set to delete to delete the stack."
    default: "create-or-update"
    required: false
  stack-name:
    description: "Name of the stack to create, update, or delete"
    required: true
  create-tag:
    description: "Should we build and tag docker images. Defaults to false and assumes images already exist."
    default: "false"
    required: false
  tag:
    description: "Specify the tag for the docker images. If not specified we will generate a default tag."
    default: ""
    required: false
  tfe-token:
    description: "TFE Token"
    required: true
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "0.20.0"
  env:
    description: "The environment to update or create"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/.github/actions/install-happy@install-happy-v1.3.1
      with:
        happy_version: ${{ inputs.happy_version }}
    - name: Create or update happy stack
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
        STACK_NAME: ${{ inputs.stack-name }}
        CREATE_TAG: ${{ inputs.create-tag }}
        TAG: ${{ inputs.tag }}
        ENV: ${{ inputs.env }}
        OPERATION: ${{ inputs.operation }}
      shell: bash
      run: |
        set -ue
        set -o pipefail
        
        IMAGE_TAG="${TAG:-sha-$GITHUB_SHA}"
        echo "Targetting Stack ${STACK_NAME}, tagging with '${IMAGE_TAG}'"
        HAPPY_DEPLOYMENT_FLAGS=""

        if [[ ${OPERATION} == "create-or-update" ]]; then
          HAPPY_DEPLOYMENT_FLAGS="--create-tag=${CREATE_TAG} --tag ${IMAGE_TAG}"
          if $(happy list --aws-profile "" --env=${ENV} 2>&1 | grep -q "^|\s*${STACK_NAME}\s*|" ); then
            OPERATION="update"
          else
            OPERATION="create"
          fi
        elif [[ ${OPERATION} == "update" || ${OPERATION} == "create" ]]; then
          HAPPY_DEPLOYMENT_FLAGS="--create-tag=${CREATE_TAG} --tag ${IMAGE_TAG}"
        fi

        echo "Starting to ${OPERATION} stack ${STACK_NAME} with additional flags: ${HAPPY_DEPLOYMENT_FLAGS}"
        happy ${OPERATION} --aws-profile "" --env=${ENV} ${HAPPY_DEPLOYMENT_FLAGS} ${STACK_NAME}
