name: Create or Update a Happy Stack
description: "Will create or update a Happy Stack"
inputs:
  tfe-token:
    description: "TFE Token"
    required: true
  stack-name:
    description: "Name of the stack to create or update"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/.github/actions/install-happy@9fd4a711d0ee9411b78d8c94a23afcd485ea93fa
    - name: Create or update happy stack
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
        STACK_NAME: ${{ inputs.stack-name }}
      shell: bash
      run: |
        set -ue
        set -o pipefail

        echo "Targetting Stack ${STACK_NAME}"

        if $(happy list --aws-profile "" | grep -q ${STACK_NAME}} ); then
          echo "Updating stack ${STACK_NAME}"
          happy update --aws-profile "" --tag sha-${GITHUB_SHA} ${STACK_NAME}
        else
          echo "Creating stack ${STACK_NAME}"
          happy create --aws-profile "" --tag sha-${GITHUB_SHA} ${STACK_NAME}
        fi
