name: Create or Update a Happy Stack
description: "Will create, update, or delete a Happy Stack"
inputs:
  stack-name:
    description: "Name of the stack to create, update, or delete"
    required: true
  create-tag:
    description: "Should we build and tag docker images. Defaults to false and assumes images already exist."
    default: "false"
    required: false
  tag:
    description: "Specify the tag for the docker images. If not specified we will generate a default tag."
    default: ""
    required: false
  tfe-token:
    description: "TFE Token"
    required: true
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "0.20.0"
  env:
    description: "The environment to update or create"
    required: false
  delete-stack:
    description: "Should we delete current stack. Defaults to false."
    default: false
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/.github/actions/install-happy@install-happy-v1.3.1
      with:
        happy_version: ${{ inputs.happy_version }}
    - name: Create or update happy stack
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
        STACK_NAME: ${{ inputs.stack-name }}
        CREATE_TAG: ${{ inputs.create-tag }}
        TAG: ${{ inputs.tag }}
        ENV: ${{ inputs.env }}
        DELETE_STACK: ${{ inputs.delete-stack }}
      shell: bash
      run: |
        set -ue
        set -o pipefail
        
        IMAGE_TAG="${TAG:-sha-$GITHUB_SHA}"
        echo "Targetting Stack ${STACK_NAME}, tagging with '${IMAGE_TAG}'"

        happy list --aws-profile "" --env=${ENV}

        if ${DELETE_STACK}; then
          echo "Deleting stack ${STACK_NAME}"
          happy delete --aws-profile "" --env=${ENV} ${STACK_NAME}
        elif $(happy list --aws-profile "" --env=${ENV} 2>&1 | grep -q "^\s*\|\s*${STACK_NAME}\s*\|" ); then
          echo "Updating stack ${STACK_NAME}"
          happy update --aws-profile "" --env=${ENV} --create-tag=${CREATE_TAG} --tag ${IMAGE_TAG} ${STACK_NAME}
        else
          echo "Creating stack ${STACK_NAME}"
          happy create --aws-profile "" --env=${ENV} --create-tag=${CREATE_TAG} --tag ${IMAGE_TAG} ${STACK_NAME}
        fi
