# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-elb-access-logs-bucket" {
  source        = "../../../modules/aws-elb-access-logs-bucket"
  bucket_policy = local.bucket_policy
  env           = local.env
  owner         = local.owner
  project       = local.project
  service       = local.service

}
