# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "bucket_arn" {
  value = module.aws-elb-access-logs-bucket.bucket_arn
}

output "bucket_name" {
  value = module.aws-elb-access-logs-bucket.bucket_name
}


