name: Create or Update a Happy Stack
description: "Will create or update a Happy Stack"
inputs:
  tfe-token:
    description: "TFE Token"
    required: true
  stack-name:
    description: "Name of the stack to create or update"
    required: true
    default: "rdev"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Install happy
      uses: chanzuckerberg/github-actions/install-happy@install-happy-v1.1.0
    - name: Create update rdev
      env:
        TFE_TOKEN: ${{ inputs.tfe-token }}
      run: |
        STACK_NAME=${GITHUB_REF#refs/heads/${{ inputs.stack-name }}-}
        if $(happy --profile="" list | grep -q $STACK_NAME); then
          echo "Updating stack $STACK_NAME"
          happy --profile=""  update --tag sha-${GITHUB_SHA} $STACK_NAME
        else
          echo "Creating stack $STACK_NAME"
          happy --profile="" create  --tag sha-${GITHUB_SHA} $STACK_NAME
        fi
