name: Create or Update a Happy Stack
description: "Will create or update a Happy Stack"
inputs:
  stackname: # id of input
    description: "Name of the stack to create or update"
    required: true
    default: "rdev"
runs:
  using: "composite"
  steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
      - name: Install happy
        uses: chanzuckerberg/github-actions/install-happy@install-happy-v1.1.0
      - name: Create update rdev
        env:
          TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
        run: |
          STACK_NAME=${GITHUB_REF#refs/heads/${{ inputs.stackname }}-}
          if $(happy --profile="" list | grep -q $STACK_NAME); then
            echo "Updating stack $STACK_NAME"
            happy --profile=""  update --tag sha-${GITHUB_SHA:0:8} $STACK_NAME
          else
            echo "Creating stack $STACK_NAME"
            happy --profile="" create  --tag sha-${GITHUB_SHA:0:8} $STACK_NAME
          fi
