# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "superset" {
  source                      = "../../../modules/superset"
  cloud_env                   = local.cloud_env
  database_ca_cert_identifier = local.database_ca_cert_identifier
  database_engine_version     = local.database_engine_version
  eks                         = local.eks
  env                         = local.env
  image_tag                   = local.image_tag
  instance_class              = local.instance_class
  k8s_core                    = local.k8s_core
  owner                       = local.owner
  project                     = local.project
  route53_zone_id             = local.route53_zone_id
  service                     = local.service
  subdomain                   = local.subdomain

}
