# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "k8s-core" {
  source                      = "../../../modules/k8s-core"
  cluster_oidc_issuer_url     = local.cluster_oidc_issuer_url
  cluster_version             = local.cluster_version
  datadog_agent_tag           = local.datadog_agent_tag
  datadog_api_key             = local.datadog_api_key
  datadog_confd_templates     = local.datadog_confd_templates
  default_namespace           = local.default_namespace
  eks_cluster_id              = local.eks_cluster_id
  env                         = local.env
  iam_role_path               = local.iam_role_path
  k8s_core_namespace          = local.k8s_core_namespace
  log_retention_in_days       = local.log_retention_in_days
  mute_dd_alerts              = local.mute_dd_alerts
  oidc_provider_arn           = local.oidc_provider_arn
  owner                       = local.owner
  pagerduty_escalation_policy = local.pagerduty_escalation_policy
  pagerduty_team              = local.pagerduty_team
  project                     = local.project
  require_network_policies    = local.require_network_policies
  route53_zone_id             = local.route53_zone_id
  service                     = local.service

}
