name: Get Terraform Version 
description: Gets the Terraform version from the current workspace in a fogg component
inputs:
  working-dir:
    description: The current working directory of the Terraform workspace
    required: true
outputs:
  tf-version:
    description: "The Terraform version in this workspace"
    value: ${{ steps.find-tf-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Find terraform version
      id: find-tf-version
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: echo "::set-output name=version::$(sed -nr 's/required_version = "=(.*)"/\1/p' fogg.tf | xargs)"