# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "kubelet_check_monitor_id" {
  value = module.datadog-k8s-cluster.kubelet_check_monitor_id
}

output "kubelet_check_monitor_url" {
  value = module.datadog-k8s-cluster.kubelet_check_monitor_url
}


