# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "datadog-k8s-cluster" {
  source                   = "../../../modules/datadog-k8s-cluster"
  cluster                  = local.cluster
  kubelet_check_thresholds = local.kubelet_check_thresholds
  mute_dd_alerts           = local.mute_dd_alerts
  notify_users             = local.notify_users
  tags                     = local.tags

}
