# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "eks-aws-config-generation" {
  source                      = "../../../modules/eks-aws-config-generation"
  aws_accounts                = local.aws_accounts
  aws_org_role_arns           = local.aws_org_role_arns
  aws_reader_role_name        = local.aws_reader_role_name
  client_id                   = local.client_id
  create_security_group       = local.create_security_group
  egress_cidrs                = local.egress_cidrs
  eks_cluster_id              = local.eks_cluster_id
  eks_worker_sgs              = local.eks_worker_sgs
  env                         = local.env
  iam_path                    = local.iam_path
  ingress_cidrs               = local.ingress_cidrs
  issuer_url                  = local.issuer_url
  lb_subnets                  = local.lb_subnets
  main_external_account_ids   = local.main_external_account_ids
  namespace                   = local.namespace
  oidc_provider_arn           = local.oidc_provider_arn
  oidc_provider_url           = local.oidc_provider_url
  owner                       = local.owner
  project                     = local.project
  registry_secretsmanager_arn = local.registry_secretsmanager_arn
  route53_zone_id             = local.route53_zone_id
  service                     = local.service
  subdomain                   = local.subdomain
  worker_external_account_ids = local.worker_external_account_ids

}
