name: argus-docker-build
description: Build a Docker Image for Argus

inputs:
  image_name:
    description: "Name of the image to build"
    required: true
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  context:
    description: "Path to the build context"
    required: true
  platform:
    description: "Platform to build for"
    required: false
    default: "linux/arm64"
  build_args:
    description: "Args for docker build"
    required: false
    default: ""
  secret_files:
    description: "Files to copy into the build context"
    required: false
    default: ""
  image_tag:
    description: "Additional tag to apply to the image this is built"
    required: true
  github_app_id:
    description: "GitHub App ID"
    required: true
  github_private_key:
    description: "GitHub App private key"
    required: true
  clean_checkout:
    description: "Whether to clean the repository before checking out"
    required: false
    default: false

outputs:
  image_uri:
    description: "URI of the image that was built"
    value: ${{ steps.ecr_metadata.outputs.IMAGE_URI }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        clean: ${{ inputs.clean_checkout }}
        fetch-depth: 0
        path: ${{ github.event.repository.name }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::533267185808:role/gh_actions_core_platform_infra_prod_eks
        role-session-name: ArgusContainerBuilder
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.github_app_id }}
        private-key: ${{ inputs.github_private_key }}
    - uses: actions/checkout@v4
      with:
        repository: chanzuckerberg/core-platform-settings
        path: core-platform-settings
        token: ${{ steps.generate_token.outputs.token }}
    - name: ECR Metadata
      id: ecr_metadata
      uses: actions/github-script@v7
      with:
        script: |
          const path = require('path');
          const ECR_REGISTRY = "533267185808.dkr.ecr.us-west-2.amazonaws.com";
          const ECR_REPO_NAME = path.join(
            'core-platform',
            '${{ github.event.repository.name }}',
            '${{ inputs.context }}',
            '${{ inputs.image_name }}',
          );
          const IMAGE_URI = `${ECR_REGISTRY}/${ECR_REPO_NAME}:${{ inputs.image_tag }}`;

          core.setOutput('ECR_REGISTRY', ECR_REGISTRY);
          core.setOutput('ECR_REPO_NAME', ECR_REPO_NAME);
          core.setOutput('IMAGE_URI', IMAGE_URI);
    - name: Create ECR repo if necessary
      uses: int128/create-ecr-repository-action@v1
      with:
        repository: ${{ steps.ecr_metadata.outputs.ECR_REPO_NAME }}
        lifecycle-policy: core-platform-settings/ecr/lifecycle-policy.json
        repository-policy: core-platform-settings/ecr/repository-policy.json
    - name: Build And Push
      uses: chanzuckerberg/github-actions/.github/actions/docker-build-push@74d720a183006c0fe0a82f52475befed7d992888
      with:
        dockerfile: ${{ github.event.repository.name }}/${{ inputs.dockerfile }}
        context: ${{ github.event.repository.name }}/${{ inputs.context }}
        name: ${{ steps.ecr_metadata.outputs.ECR_REPO_NAME }}
        registry: ${{ steps.ecr_metadata.outputs.ECR_REGISTRY }}
        custom_tag: ${{ inputs.image_tag }}
        platforms: ${{ inputs.platform }}
        build_args: |
          IMAGE_TAG=${{ inputs.image_tag }}
          ${{ inputs.build_args }}
        secret-files: ${{ inputs.secret_files }}

    # TODO: scan image for vulnerabilities
    # - name: Scan for vulnerabilities
    #   uses: chanzuckerberg/github-actions/.github/actions/argus-builder/scan-for-vulnerabilities@main
    #   with:
    #     image_uri: ${{ steps.ecr_metadata.outputs.ECR_REGISTRY }}/${{ steps.ecr_metadata.outputs.ECR_REPO_NAME }}:${{ inputs.image_tag }}
    #     github_app_id: ${{ inputs.github_app_id }}
    #     github_private_key: ${{ inputs.github_private_key }}
