# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
provider "aws" {

  region = "us-east-1"


  assume_role {
    role_arn = "arn:aws:iam::340591210379:role/tfe-si"
  }

  allowed_account_ids = ["340591210379"]
}
# Aliased Providers (for doing things in every region).

terraform {
  required_version = "=0.13.5"

  backend "remote" {

    hostname     = "si.prod.tfe.czi.technology"
    organization = "shared-infra"
    workspaces {
      name = "preprod-test2"
    }

  }
  required_providers {

    archive = {
      source = "hashicorp/archive"

      version = "~> 2.0"

    }

    assert = {
      source = "bwoznicki/assert"

      version = "~> 0.0.1"

    }

    aws = {
      source = "hashicorp/aws"

      version = "3.63.0"

    }

    local = {
      source = "hashicorp/local"

      version = "~> 2.0"

    }

    null = {
      source = "hashicorp/null"

      version = "~> 3.0"

    }

    okta-head = {
      source = "okta/okta"

      version = "~> 3.30"

    }

    random = {
      source = "hashicorp/random"

      version = "~> 2.2"

    }

    template = {
      source = "hashicorp/template"

      version = "~> 2.2"

    }

    tls = {
      source = "hashicorp/tls"

      version = "~> 3.0"

    }

  }
}
variable "env" {
  type    = string
  default = "preprod"
}
variable "project" {
  type    = string
  default = "ie"
}
variable "region" {
  type    = string
  default = "us-east-1"
}
variable "component" {
  type    = string
  default = "test2"
}
variable "owner" {
  type    = string
  default = "infra-eng@chanzuckerberg.com"
}
variable "tags" {
  type = object({ project : string, env : string, service : string, owner : string, managedBy : string })
  default = {
    project   = "ie"
    env       = "preprod"
    service   = "test2"
    owner     = "infra-eng@chanzuckerberg.com"
    managedBy = "terraform"
  }
}
variable "aws_cloudtrail_bucket_name" {
  type    = string
  default = "czi-logs-cloudtrail"
}
variable "aws_cloudtrail_s3_encryption_key_arn" {
  type    = string
  default = "arn:aws:kms:us-west-2:724328632434:key/5e9e938a-441e-4ffd-96b3-8e38b951301e"
}
variable "aws_config_bucket_name" {
  type    = string
  default = "czi-aws-config"
}
variable "aws_github_bucket_name" {
  type    = string
  default = "shared-infra-logs-github-webhooks-archiver"
}
variable "aws_org_id" {
  type    = string
  default = "o-56v5gp5fcu"
}
variable "eks_cluster_name" {
  type    = string
  default = "ie-connections-prod"
}
variable "ie_pd_default_escalation" {
  type    = string
  default = "[Infra] Core Infra Eng"
}
variable "ie_pd_team" {
  type    = string
  default = "Infra Eng"
}
variable "learning_platform_aws_org_id" {
  type    = string
  default = "o-iqjigxi1d8"
}
data "terraform_remote_state" "global" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "shared-infra"
    workspaces = {
      name = "global"
    }

  }
}
data "terraform_remote_state" "test1" {
  backend = "remote"
  config = {


    hostname     = "si.prod.tfe.czi.technology"
    organization = "shared-infra"
    workspaces = {
      name = "preprod-test1"
    }

  }
}
variable "aws_accounts" {
  type = map(string)
  default = {

  }
}
