# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.
provider "aws" {

  region  = "us-east-1"
  profile = "test1"

  allowed_account_ids = ["340591210379"]
}
# Aliased Providers (for doing things in every region).

terraform {
  required_version = "=0.13.5"

  backend "s3" {

    bucket         = "blah"
    dynamodb_table = ""
    key            = "terraform/ie/envs/preprod/components/test2.tfstate"
    encrypt        = true
    region         = "us-west-2"
    profile        = "test1"


  }
  required_providers {

    archive = {
      source = "hashicorp/archive"

      version = "~> 2.0"

    }

    assert = {
      source = "bwoznicki/assert"

      version = "~> 0.0.1"

    }

    aws = {
      source = "hashicorp/aws"

      version = "2.47.0"

    }

    local = {
      source = "hashicorp/local"

      version = "~> 2.0"

    }

    null = {
      source = "hashicorp/null"

      version = "~> 3.0"

    }

    okta-head = {
      source = "okta/okta"

      version = "~> 3.30"

    }

    random = {
      source = "hashicorp/random"

      version = "~> 2.2"

    }

    template = {
      source = "hashicorp/template"

      version = "~> 2.2"

    }

    tls = {
      source = "hashicorp/tls"

      version = "~> 3.0"

    }

  }
}
variable "env" {
  type    = string
  default = "preprod"
}
variable "project" {
  type    = string
  default = "ie"
}
variable "region" {
  type    = string
  default = "us-east-1"
}
variable "component" {
  type    = string
  default = "test2"
}
variable "aws_profile" {
  type    = string
  default = "test1"
}
variable "owner" {
  type    = string
  default = "test1"
}
variable "tags" {
  type = object({ project : string, env : string, service : string, owner : string, managedBy : string })
  default = {
    project   = "ie"
    env       = "preprod"
    service   = "test2"
    owner     = "test1"
    managedBy = "terraform"
  }
}
variable "eks_cluster_name" {
  type    = string
  default = "ie-connections-prod"
}
data "terraform_remote_state" "global" {
  backend = "s3"
  config = {


    bucket         = "blah"
    dynamodb_table = ""
    key            = "terraform/test1/global.tfstate"
    region         = "us-west-2"
    profile        = "test1"


  }
}
data "terraform_remote_state" "test1" {
  backend = "s3"
  config = {


    bucket         = "blah"
    dynamodb_table = ""
    key            = "terraform/ie/envs/preprod/components/test1.tfstate"
    region         = "us-west-2"
    profile        = "test1"


  }
}
variable "aws_accounts" {
  type = map(string)
  default = {

  }
}
