name: 'Archived Repository Scanner'
description: 'Scans for GitHub.com links in the repository and creates security vulnerabilities for archived repositories'
author: 'CZI'

inputs:
  github_token:
    description: 'GitHub token for API access (can be GITHUB_TOKEN or GitHub App token)'
    required: false
    default: ${{ github.token }}
  exclude_patterns:
    description: 'Comma-separated list of file patterns to exclude'
    required: false
    default: '.git/**,node_modules/**,dist/**,build/**,*.log'
  fail_on_archived:
    description: 'Whether the action should fail when archived repositories are found'
    required: false
    default: 'true'

outputs:
  archived_repos_found:
    description: 'Number of archived repositories found'
  sarif_file_path:
    description: 'Path to the generated SARIF file'
  total_github_links:
    description: 'Total number of GitHub links found'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'archive'
  color: 'red' 