# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "cluster_arn" {
  value = module.eks-cluster.cluster_arn
}

output "cluster_ca" {
  value = module.eks-cluster.cluster_ca
}

output "cluster_endpoint" {
  value = module.eks-cluster.cluster_endpoint
}

output "cluster_iam_role_name" {
  value = module.eks-cluster.cluster_iam_role_name
}

output "cluster_id" {
  value = module.eks-cluster.cluster_id
}

output "cluster_oidc_issuer_url" {
  value = module.eks-cluster.cluster_oidc_issuer_url
}

output "cluster_security_group" {
  value = module.eks-cluster.cluster_security_group
}

output "cluster_version" {
  value = module.eks-cluster.cluster_version
}

output "kubeconfig" {
  value = module.eks-cluster.kubeconfig
}

output "oidc_provider_arn" {
  value = module.eks-cluster.oidc_provider_arn
}

output "secrets_key_arn" {
  value = module.eks-cluster.secrets_key_arn
}

output "worker_iam_role_name" {
  value = module.eks-cluster.worker_iam_role_name
}

output "worker_security_group" {
  value = module.eks-cluster.worker_security_group
}


