name: validate-json-schema
description: Validate that a given JSON object matches a given AJV schema

inputs:
  data:
    description: The JSON to validate
    required: true
  schema:
    description: The AJV schema to validate json against
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
