# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-env" {
  source                              = "git@github.com:chanzuckerberg/shared-infra//terraform/modules/aws-env?ref=v0.143.0"
  azs                                 = local.azs
  bastion_allowed_ingress_cidr_blocks = local.bastion_allowed_ingress_cidr_blocks
  bastion_instance_type               = local.bastion_instance_type
  bastion_ssh_users                   = local.bastion_ssh_users
  bastion_subdomain                   = local.bastion_subdomain
  create_database_subnet_route_table  = local.create_database_subnet_route_table
  database_subnet_cidrs               = local.database_subnet_cidrs
  datadog_api_key                     = local.datadog_api_key
  disable_auto_security_update        = local.disable_auto_security_update
  enable_dynamodb_endpoint            = local.enable_dynamodb_endpoint
  enable_s3_endpoint                  = local.enable_s3_endpoint
  env                                 = local.env
  k8s_cluster_names                   = local.k8s_cluster_names
  owner                               = local.owner
  private_subnet_cidrs                = local.private_subnet_cidrs
  project                             = local.project
  public_subnet_cidrs                 = local.public_subnet_cidrs
  region                              = local.region
  service                             = local.service
  ssh_key_name                        = local.ssh_key_name
  vpc_cidr                            = local.vpc_cidr
  vpc_flow_log_retention_in_days      = local.vpc_flow_log_retention_in_days
  zone_id                             = local.zone_id

}
