name: argus-builder-manifest-update
description: Updates manifests for Argus after the Docker image is built

inputs:
  envs:
    description: 'Env names, comma delimited'
    required: true
  image_tag:
    description: The tag of the image that should be updated
    required: true
  images:
    description: TODO
    required: true
  should_build:
    description: TODO
    required: true
  should_deploy:
    description: TODO
    required: true
  build_result:
    description: TODO
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
