name: argus-builder-manifest-update
description: Updates manifests for Argus after the Docker image is built

inputs:
  envs:
    description: 'Env names, comma delimited'
    required: true
  image_tag:
    description: The tag of the image that should be updated
    required: true
  argus_project_dirs:
    description: 'Comma-delimited list of Argus project roots (directories that contain the .infra/ directory for each app)'
    default: '.'
    required: false
  github_app_id:
    description: 'GitHub App ID'
    required: true
  github_private_key:
    description: 'GitHub App private key'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
