# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-kafka" {
  source                                    = "../../../modules/aws-kafka"
  cluster_name                              = local.cluster_name
  ebs_volume_size                           = local.ebs_volume_size
  env                                       = local.env
  ingress_cidr_blocks                       = local.ingress_cidr_blocks
  kafka_configs                             = local.kafka_configs
  kafka_username                            = local.kafka_username
  kafka_version                             = local.kafka_version
  number_of_broker_nodes                    = local.number_of_broker_nodes
  project                                   = local.project
  service                                   = local.service
  subnet_ids                                = local.subnet_ids
  tags                                      = local.tags
  vpc_id                                    = local.vpc_id
  write_aws_ssm_parameter_bootstrap_servers = local.write_aws_ssm_parameter_bootstrap_servers
  write_aws_ssm_parameter_jaas_config       = local.write_aws_ssm_parameter_jaas_config
  write_aws_ssm_parameter_password          = local.write_aws_ssm_parameter_password
  write_aws_ssm_parameter_username          = local.write_aws_ssm_parameter_username

}
