# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "bootstrap_servers" {
  value = module.aws-kafka.bootstrap_servers
}

output "zookeeper_connect_string" {
  value = module.aws-kafka.zookeeper_connect_string
}


