# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "eks-debezium" {
  source                     = "../../../modules/eks-debezium"
  aws_ssm_iam_role_name      = local.aws_ssm_iam_role_name
  cluster_oidc_issuer_url    = local.cluster_oidc_issuer_url
  config_storage_topic       = local.config_storage_topic
  custom_kafka_config        = local.custom_kafka_config
  debezium_image_tag         = local.debezium_image_tag
  eks_cluster_id             = local.eks_cluster_id
  env                        = local.env
  group_id                   = local.group_id
  jmx_host                   = local.jmx_host
  jmx_port                   = local.jmx_port
  nginx_auth_proxy_image_tag = local.nginx_auth_proxy_image_tag
  offset_flush_interval_ms   = local.offset_flush_interval_ms
  offset_flush_timeout_ms    = local.offset_flush_timeout_ms
  offset_storage_topic       = local.offset_storage_topic
  oidc_provider_arn          = local.oidc_provider_arn
  owner                      = local.owner
  project                    = local.project
  route53_zone_id            = local.route53_zone_id
  service                    = local.service
  statsd_host                = local.statsd_host
  statsd_port                = local.statsd_port
  statsd_prefix              = local.statsd_prefix
  status_storage_topic       = local.status_storage_topic
  subdomain                  = local.subdomain

}
