# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "eks-jupyterhub" {
  source                      = "../../../modules/eks-jupyterhub"
  aws_ssm_iam_role_name       = local.aws_ssm_iam_role_name
  cluster_oidc_issuer_url     = local.cluster_oidc_issuer_url
  create_security_group       = local.create_security_group
  egress_cidrs                = local.egress_cidrs
  eks_cluster_id              = local.eks_cluster_id
  eks_worker_sgs              = local.eks_worker_sgs
  env                         = local.env
  ingress_cidrs               = local.ingress_cidrs
  lb_subnets                  = local.lb_subnets
  oidc_provider_arn           = local.oidc_provider_arn
  owner                       = local.owner
  project                     = local.project
  registry_secretsmanager_arn = local.registry_secretsmanager_arn
  route53_zone_id             = local.route53_zone_id
  service                     = local.service
  subdomain                   = local.subdomain

}
