# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "airflow_master_role" {
  value = module.eks-airflow.airflow_master_role
}

output "airflow_task_role" {
  value = module.eks-airflow.airflow_task_role
}

output "dashboard_url" {
  value = module.eks-airflow.dashboard_url
}


