name: argus-builder/build-prep
description: |
  TODO

inputs:
  github_token:
    description: The GitHub token for authenticating with the GitHub API
    required: true
  images:
    description: 'JSON object specifying the images to build'
    required: true
  path_filters:
    description: 'Glob patterns to match against changed files in the repository, comma delimited'
    required: false
    default: '**/*'
  path_filters_base:
    description: |
      Git reference (e.g. branch name) against which the changes will be detected. Defaults to the current branch.
      If it references same branch it was pushed to, changes are detected against the most recent commit before the push.
      This option is ignored if action is triggered by pull_request event.
    required: false
    default: ${{ github.ref }}
  branches_include:
    description: 'Branch names to run this job on, supports wildcards, comma delimited'
    required: false
    default: '*'
  branches_ignore:
    description: 'Branch names to run this job on, supports wildcards, comma delimited'
    required: false
    default: ''
  manifest_trigger_labels:
    description: |
      Labels that will trigger updating the manifest and committing a docker image change to values.yaml, comma delimited.
      If ANY of the labels are found on the PR, the manifest will be updated.
    required: false
    default: 'stack'

outputs:
  image_tag:
    description: A custom tag to apply to the images that are built
  should_build:
    description: Whether the build should run
  should_deploy:
    description: Whether or not the image tag should be written to the manifest
  images:
    description: Processed images object

runs:
  using: 'node20'
  main: 'dist/index.js'
