# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "certificate_arn" {
  value = module.eks-debezium.certificate_arn
}

output "debezium_role" {
  value = module.eks-debezium.debezium_role
}

output "k8s_service" {
  value = module.eks-debezium.k8s_service
}


