# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "aws-elasticache-redis-cluster" {
  source                      = "../../../modules/aws-elasticache-redis-cluster"
  allowed_ingress_cidr_blocks = local.allowed_ingress_cidr_blocks
  auth_token                  = local.auth_token
  env                         = local.env
  id                          = local.id
  instance_type               = local.instance_type
  num_node_groups             = local.num_node_groups
  owner                       = local.owner
  parameter_group_family      = local.parameter_group_family
  parameters                  = local.parameters
  project                     = local.project
  redis_version               = local.redis_version
  replicas_per_node_group     = local.replicas_per_node_group
  service                     = local.service
  snapshot_retention_days     = local.snapshot_retention_days
  vpc_id                      = local.vpc_id
  vpc_subnet_ids              = local.vpc_subnet_ids

}
