# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "amundsen" {
  source               = "../../../modules/amundsen"
  alerting             = local.alerting
  cloud-env            = local.cloud-env
  eks                  = local.eks
  env                  = local.env
  helm_release_version = local.helm_release_version
  k8s-core             = local.k8s-core
  owner                = local.owner
  project              = local.project
  route53_zone_id      = local.route53_zone_id
  service              = local.service
  ssl_policy           = local.ssl_policy
  subdomain            = local.subdomain

}
