name: Lint Helm YAML
description: Run helm lint on the chart at a given path
inputs:
  chart_path:
    description: The path of the chart
    required: true
    type: string
  values_files:
    description: The set of values files represented as a set of strings separated by a comma
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4
    - name: Helm lint
      shell: bash
      working-directory: ${{ inputs.chart_path }}
      run: |
        set -ue
        set -o pipefail

        helm dependency update .
        # produces `helm lint . -f file1 -f file2` with values_files as file1,file2
        helm lint . $(echo "${{ inputs.values_files }}" | sed 's/,/ -f /g' | sed 's/^/-f /') \
          --set global.argoBuildEnv.appName=mockappname \
                --set global.argoBuildEnv.appNamespace=mocknamespace \
                --set global.argoBuildEnv.appRevision=0.0.0 \
                --set global.argoBuildEnv.appRevisionShort=mockrevshort \
                --set global.argoBuildEnv.appRevisionShort8=mockrev8 \
                --set global.argoBuildEnv.appSourcePath=mocksourcepath \
                --set global.argoBuildEnv.appSourceRepoUrl=mocksourcerepourl \
                --set global.argoBuildEnv.appSourceTargetRevision=mocktargetrevision \
                --set global.argusMetadata.appName=mockappname \
                --set global.argusMetadata.appNamespace=mocknamespace \
                --set global.argusMetadata.stackName=mockstackname \
                --set global.argusMetadata.repoName=mockreponame \
                --set global.argusMetadata.repoOwner=mockrepoowner \
                --set global.appSecrets.clusterCLISecret.secretKey=mockclustercli \
                --set global.appSecrets.clusterCLISecret.secretName=mockclustercliname \
                --set global.appSecrets.clusterSecret.secretKey=mockcluster \
                --set global.appSecrets.clusterSecret.secretName=mockclustername \
                --set global.appSecrets.envSecret.secretKey=mockenv \
                --set global.appSecrets.envSecret.secretName=mockenvname \
                --set global.appSecrets.stackSecret.secretKey=mockstack \
                --set global.appSecrets.stackSecret.secretName=mockstackname
