name: Lint Helm YAML
description: Run helm lint on the chart at a given path
inputs:
  chart_path:
    description: The path of the chart
    required: true
    type: string
  values_files:
    description: The set of values files represented as a set of strings separated by a comma
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4
    - name: Helm lint
      shell: bash
      working-directory: ${{ inputs.chart_path }}
      run: |
        set -ue
        set -o pipefail

        helm dependency update .
        # produces `helm lint . -f file1 -f file2` with values_files as file1,file2
        helm lint . $(echo "${{ inputs.values_files }}" | sed 's/,/ -f /g' | sed 's/^/-f /')
