# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "rancher" {
  source          = "../../../modules/rancher"
  cloud_env       = local.cloud_env
  eks_env         = local.eks_env
  namespace       = local.namespace
  rancher_fqdn    = local.rancher_fqdn
  rancher_version = local.rancher_version
  route53_zone_id = local.route53_zone_id
  tags            = local.tags

}
