# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "myscript-proxy" {
  source              = "../../../modules/myscript-proxy"
  aws_route53_zone_id = local.aws_route53_zone_id
  proxy_domain_prefix = local.proxy_domain_prefix
  tags                = local.tags

}
