# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "mwaa_environment_arn" {
  value = module.aws-mwaa.mwaa_environment_arn
}

output "mwaa_environment_name" {
  value = module.aws-mwaa.mwaa_environment_name
}

output "mwaa_execution_role" {
  value = module.aws-mwaa.mwaa_execution_role
}

output "mwaa_s3_bucket" {
  value = module.aws-mwaa.mwaa_s3_bucket
}

output "mwaa_subnet_arns" {
  value = module.aws-mwaa.mwaa_subnet_arns
}

output "mwaa_webserver_url" {
  value = module.aws-mwaa.mwaa_webserver_url
}


