# .github/actions/csv-vulnerability-filter/action.yml
name: 'Filter CSV Vulnerability Reports & Generate Details Table (Simple)'
description: 'Filters vulnerability CSVs (assuming fixed column names), optionally ignores unpatched, handles missing comparison, checks thresholds, and generates a detailed Markdown findings table.'
author: 'Your Company Name or Your Name' # Optional: Customize this

inputs:
  # --- File Inputs ---
  primary_csv_path:
    description: 'Path to the CSV file containing the primary vulnerability scan results.'
    required: true
  comparison_csv_path: # Now optional in logic, but still an input
    description: 'Path to the CSV file containing the baseline/comparison vulnerability scan results. If empty or unparsable, comparison is skipped.'
    required: false # Make it not strictly required by the action runner itself
    default: ''     # Default to empty string

  # --- Filtering/Processing Options ---
  ignore_unpatched:
    description: 'If true, vulnerabilities without a value in the fixed_ver column will be excluded from threshold checks and final filtered outputs.'
    required: false
    default: 'false' # Default is not to ignore them

  # --- Threshold Inputs ---
  # Assumes threshold check uses the 'severity' column from the CSV
  critical_threshold:
    description: 'Max allowable CRITICAL count in filtered results. Set to -1 to disable check.'
    required: false
    default: '-1'
  high_threshold:
    description: 'Max allowable HIGH count in filtered results. Set to -1 to disable check.'
    required: false
    default: '-1'
  medium_threshold:
    description: 'Max allowable MEDIUM count in filtered results. Set to -1 to disable check.'
    required: false
    default: '-1'
  low_threshold:
    description: 'Max allowable LOW count in filtered results. Set to -1 to disable check.'
    required: false
    default: '-1'

outputs:
  # Outputs reflect the final state after all filtering
  filtered_results_csv_path:
    description: 'Path to the generated CSV file containing vulnerabilities unique to the primary scan (after any filtering).'
  filtered_results_markdown:
    description: 'Markdown table detailing the unique (filtered) vulnerabilities (after any filtering).'
  filtered_count:
    description: 'The number of unique (filtered) vulnerabilities found (after any filtering).'
  removed_results_csv_path:
    description: 'Path to the generated CSV file containing vulnerabilities common to both scans (empty if comparison skipped).'
  removed_results_markdown:
    description: 'Markdown table detailing the common (removed) vulnerabilities (indicates if comparison skipped).'
  removed_count:
    description: 'The number of common (removed) vulnerabilities found (0 if comparison skipped).'
  vulnerability_threshold_exceeded:
    description: 'Boolean indicating if any vulnerability count threshold was met or exceeded by the final filtered results.'

runs:
  using: 'node20' # Or 'node16'
  main: 'dist/index.js'

branding: # Optional: Customize
  icon: 'filter'
  color: 'green'