# .github/actions/csv-vulnerability-filter/action.yml
name: 'Filter CSV Vulnerability Reports'
description: 'Filters a primary vulnerability CSV report against a baseline comparison CSV report based on common identifiers.'
author: 'Your Company Name or Your Name' # Optional: Customize this

inputs:
  primary-csv-path:
    description: 'Path to the CSV file containing the primary vulnerability scan results.'
    required: true
  comparison-csv-path:
    description: 'Path to the CSV file containing the baseline/comparison vulnerability scan results.'
    required: false
  cve-column-name:
    description: 'The exact column name in both CSVs that contains the CVE ID or primary vulnerability identifier.'
    required: true
    default: 'CVE ID' # Common default, adjust if needed
  package-column-name:
    description: 'The exact column name in both CSVs that contains the affected package name.'
    required: true
    default: 'Package Name' # Common default, adjust if needed
  # Optional: Add version column if stricter matching is desired
  # version-column-name:
  #   description: 'Optional: The exact column name for the package version for stricter filtering.'
  #   required: false

outputs:
  filtered-results-csv-path:
    description: 'Path to the generated CSV file containing vulnerabilities unique to the primary scan.'
  filtered-results-markdown:
    description: 'Markdown summary of the unique (filtered) vulnerabilities.'
  filtered-count:
    description: 'The number of unique (filtered) vulnerabilities found.'
  removed-results-csv-path:
    description: 'Path to the generated CSV file containing vulnerabilities common to both scans (i.e., removed from the primary list).'
  removed-results-markdown:
    description: 'Markdown summary of the common (removed) vulnerabilities.'
  removed-count:
    description: 'The number of common (removed) vulnerabilities found.'

runs:
  using: 'node20' # Or 'node16'
  main: 'dist/index.js'

branding: # Optional: Customize
  icon: 'filter'
  color: 'green'