# .github/actions/csv-vulnerability-filter/action.yml
name: 'Filter CSV Vulnerability Reports & Generate Details Table (Simple)'
description: 'Filters vulnerability CSVs (assuming fixed column names), optionally ignores unpatched, handles missing comparison, checks thresholds, and generates a detailed Markdown findings table.'
author: 'Your Company Name or Your Name'

inputs:
  # --- File Inputs ---
  primary-csv-path:
    description: 'Path to the CSV file containing the primary vulnerability scan results.'
    required: true
  comparison-csv-path: # Now optional in logic, but still an input
    description: 'Path to the CSV file containing the baseline/comparison vulnerability scan results. If empty or unparsable, comparison is skipped.'
    required: false # Make it not strictly required by the action runner itself
    default: ''     # Default to empty string

  # --- Filtering/Processing Options ---
  ignore-unpatched: # <-- ADDED INPUT
    description: 'If true, vulnerabilities without a value in the fixed_ver column will be excluded from threshold checks and final filtered outputs.'
    required: false
    default: 'false' # Default is not to ignore them

  # --- Threshold Inputs ---
  # Assumes threshold check uses the 'severity' column from the CSV
  critical-threshold:
    description: 'Max allowable CRITICAL count. Set to -1 to disable.'
    required: false
    default: '-1'
  high-threshold:
    description: 'Max allowable HIGH count. Set to -1 to disable.'
    required: false
    default: '-1'
  medium-threshold:
    description: 'Max allowable MEDIUM count. Set to -1 to disable.'
    required: false
    default: '-1'
  low-threshold:
    description: 'Max allowable LOW count. Set to -1 to disable.'
    required: false
    default: '-1'

outputs:
  # Outputs remain the same
  filtered-results-csv-path:
    description: 'Path to the generated CSV file containing vulnerabilities unique to the primary scan (after any filtering).'
  filtered-results-markdown:
    description: 'Markdown table detailing the unique (filtered) vulnerabilities (after any filtering).'
  filtered-count:
    description: 'The number of unique (filtered) vulnerabilities found (after any filtering).'
  removed-results-csv-path:
    description: 'Path to the generated CSV file containing vulnerabilities common to both scans (empty if comparison skipped).'
  removed-results-markdown:
    description: 'Markdown table detailing the common (removed) vulnerabilities (indicates if comparison skipped).'
  removed-count:
    description: 'The number of common (removed) vulnerabilities found (0 if comparison skipped).'
  vulnerability-threshold-exceeded:
    description: 'Boolean indicating if any vulnerability count threshold was met or exceeded by the final filtered results.'

runs:
  using: 'node20'
  main: 'dist/index.js'