name: Downloads and installs Happy CLI
description: "Will download and install Happy CLI."
inputs:
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "0.13.0"
runs:
  using: "composite"
  steps:
    - name: Install happy
      shell: bash
      run: |
        set -ue
        cd $(mktemp -d)
        wget --quiet https://github.com/chanzuckerberg/happy/releases/download/v${{ inputs.happy_version }}/happy_${{ inputs.happy_version }}_linux_amd64.tar.gz -O happy.tar.gz
        tar -xf happy.tar.gz
        echo "${PWD}" >> "${GITHUB_PATH}"
