name: Downloads and installs Happy CLI
description: "Will download and install Happy CLI."
inputs:
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "latest"
  install_globally:
    description: "Whether to add happy to the system bin directory"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install gh CLI
      run: |
        VERSION="2.30.0"
        AMD_CMD="curl https://github.com/cli/cli/releases/download/v$VERSION/gh_$VERSION_linux_amd64.tar.gz -o /tmp/ghcli.tar.gz"
        ARM_CMD="curl https://github.com/cli/cli/releases/download/v$VERSION/gh_$VERSION_linux_arm64.tar.gz -o /tmp/ghcli.tar.gz"
        PLATFORM=$(uname -m)
        if [[ $PLATFORM == "arm64" ]]; then
            $($ARM_CMD)
        elif [[ $PLATFORM == "aarch64" ]]; then
            $($ARM_CMD)
        else
            $($AMD_CMD)
        fi
        sudo mkdir /opt/ghcli/
        sudo tar -xf /tmp/ghcli.tar.gz -C /opt/ghcli
        echo "/opt/ghcli/bin" >> $GITHUB_PATH
    - name: Install terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0
    - name: Install AWS CLI v2
      shell: bash
      run:  |
        AMD_CMD="curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip"
        ARM_CMD="curl https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o /tmp/awscliv2.zip"
        PLATFORM=$(uname -m)
        if [[ $PLATFORM == "arm64" ]]; then
            $($ARM_CMD)
        elif [[ $PLATFORM == "aarch64" ]]; then
            $($ARM_CMD)
        else
            $($AMD_CMD)
        fi
        unzip -q /tmp/awscliv2.zip -d /tmp
        rm /tmp/awscliv2.zip
        sudo /tmp/aws/install --update
        rm -rf /tmp/aws/
    - name: Install happy
      shell: bash
      env:
        HAPPY_VERSION: ${{ inputs.happy_version }}
        INSTALL_SYSTEMWIDE: ${{ inputs.install_globally }}
        GH_TOKEN: ${{ github.token }}
      # TODO: cache as in:
      #       https://docs.github.com/en/actions/creating-actions/developing-a-third-party-cli-action
      run: |
        set -ue
        cd $(mktemp -d)
        echo Input argument indicated to use Happy version: $HAPPY_VERSION
        if [ -z $HAPPY_VERSION ] || [ $HAPPY_VERSION == "latest" ]
        then
          HAPPY_VERSION=$(gh api -H "Accept: application/vnd.github.v3+json" /repos/chanzuckerberg/happy/releases --paginate -q "[.[] | select(.tag_name | startswith(\"cli-v\")) | .tag_name][0]" | sed -e "s/^[a-z\-]*v//" | head -n 1)
        fi
        PLATFORM=$(uname -m)
        echo Installing Happy version: $HAPPY_VERSION
        echo Installing Happy platform: $PLATFORM
        ARM_CMD="wget --quiet https://github.com/chanzuckerberg/happy/releases/download/v${HAPPY_VERSION}/happy_${HAPPY_VERSION}_linux_arm64.tar.gz -O happy.tar.gz"
        AMD_CMD="wget --quiet https://github.com/chanzuckerberg/happy/releases/download/v${HAPPY_VERSION}/happy_${HAPPY_VERSION}_linux_amd64.tar.gz -O happy.tar.gz"
        if [[ $PLATFORM == "arm64" ]]; then
            $($ARM_CMD)
        elif [[ $PLATFORM == "aarch64" ]]; then
            $($ARM_CMD)
        else
            $($AMD_CMD)
        fi
        tar -xf happy.tar.gz
        echo "${PWD}" >> "${GITHUB_PATH}"
        if [ -n "${INSTALL_SYSTEMWIDE}" ]; then
            cp happy /usr/local/bin/
        fi
