name: Downloads and installs Happy CLI
description: "Will download and install Happy CLI."
runs:
  using: "composite"
  steps:
    - name: Install happy
      shell: bash
      run: |
        wget https://github.com/chanzuckerberg/happy/releases/download/v0.12.0/happy_0.12.0_darwin_amd64.tar.gz -O happy.tar.gz
        tar -xf happy.tar.gz
        ls -la
        pwd
        echo "${PWD}" >> "${GITHUB_PATH}"
