name: Downloads and installs Happy CLI
description: "Will download and install Happy CLI."
inputs:
  happy_version:
    description: "Version of happy CLI to fetch"
    required: true
    default: "0.16.0"
runs:
  using: "composite"
  steps:
    - name: Install happy
      shell: bash
      env:
        HAPPY_VERSION: ${{ inputs.happy_version }}
      # TODO: cache as in:
      #       https://docs.github.com/en/actions/creating-actions/developing-a-third-party-cli-action
      run: |
        set -ue
        cd $(mktemp -d)
        wget --quiet https://github.com/chanzuckerberg/happy/releases/download/v${HAPPY_VERSION}/happy_${HAPPY_VERSION}_linux_amd64.tar.gz -O happy.tar.gz
        tar -xf happy.tar.gz
        echo "${PWD}" >> "${GITHUB_PATH}"
# test
