# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "aws_ssm_iam_role_name" {
  value = module.k8s-core.aws_ssm_iam_role_name
}

output "datadog_agent_hostname" {
  value = module.k8s-core.datadog_agent_hostname
}

output "default_namespace" {
  value = module.k8s-core.default_namespace
}


