# Validates PR title follows conventional commits
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  conventional_commit_title:
    runs-on: [ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/conventional-commits
