# Validates PR title follows conventional commits
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  conventional_commit_title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/conventional-commits
      - uses: ./.github/actions/conventional-commits
        with:
          enforce_identifier_prefixes: |
            CCIE
            CDI
