on: 
  push: 
    branches: 
      - fogg-*

concurrency:
  group: ${{ github.ref }}

jobs:
  fogg-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.CZI_GITHUB_HELPER_APP_ID }}
          private_key: ${{ secrets.CZI_GITHUB_HELPER_PK }}
      - uses: ./.github/actions/fogg-apply
        with: 
          github-token: ${{ steps.generate_token.outputs.token }}
  get-changed-fogg-components:
    runs-on: ubuntu-latest
    outputs:
      tfe-workspaces: ${{ steps.get-changed-fogg-components.outputs.tfe-workspaces }}
    steps:
      - uses: actions/checkout@v3
      - name: get-changed-fogg-components
        id: get-changed-fogg-components
        uses: ./.github/actions/get-changed-fogg-components
  tf-test-changed-dirs:
    runs-on: ubuntu-latest
    needs: get-changed-fogg-components
    strategy:
      matrix:
        workspace: ${{ fromJson(needs.get-changed-fogg-components.outputs.tfe-workspaces) }}
    if: ${{ needs.find-changed-dirs.outputs.allChanges != '[]' }}
    steps:
      - uses: actions/checkout@v3
      - name: get-tf-version-fogg
        id: get-tf-version-fogg
        uses: ./.github/actions/get-tf-version-fogg
        with:
          working-dir: ${{matrix.workspace}}
      - name: tf-test
        id: tf-test
        uses: ./.github/actions/tf-test
        with:
          ssh-private-key: ${{secrets.SHARED_INFRA_DEPLOY_KEY}}
          working-dir: ${{matrix.workspace}}
          tf-version: ${{steps.get_tf_version.outputs.tf-version}}
          tfe-token: ${{secrets.TFE_TOKEN}}