on:
  pull_request: {}

name: Test Install Happy
jobs:
  test-install-happy-latest:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-happy
      - run: happy version
      - run: gh auth status
  test-install-happy-pinned:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-happy
        with:
          happy_version: "1.81.0"
      - run: happy version
      - run: gh auth status
  test-install-happy-x64:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-happy
      - run: happy version
      - run: gh auth status
