on:
  pull_request: {}

name: Test Install Happy
jobs:
  test-install-happy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-happy/action.yml
      - run: happy version
