on:
  pull_request: {}

name: Test Install Happy
jobs:
  test-install-happy-latest:
    runs-on: [ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/install-happy
      - run: happy version
      - run: gh auth status
  test-install-happy-pinned:
    runs-on: [ARM64]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/install-happy
        with:
          happy_version: "0.81.0"
      - run: happy version
      - run: gh auth status
  test-install-happy-amd64:
    runs-on: [amd64]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: ./.github/actions/install-happy
      - run: happy version
      - run: gh auth status
