on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        id: configure-changelog
        with:
          result-encoding: string
          script: |
            const changelogTypes = [
              {type: "feat", section: "Features", hidden: false},
              {type: "chore", section: "Misc", hidden: false},
              {type: "fix", section: "BugFixes", hidden: false},
            ]

            return JSON.stringify(changelogTypes)

      - name: release please
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: simple
          command: manifest
          bump-minor-pre-major: true
          changelog-types: ${{ steps.configure-changelog.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
          monorepo-tags: true
