name: 'Secrets Scan Reporter'
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened

jobs:
  secret-scanning-review:
    # PRs from forks will not have visibility to secrets.* and will fail
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ARM64
    permissions: {}
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GH_ACTIONS_HELPER_APP_ID }}
          private-key: ${{ secrets.GH_ACTIONS_HELPER_PK }}
      - name: 'Secret Scanning Review Action'
        uses: chanzuckerberg/secret-scanning-review-action@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python'
