name: 'Secret Scanning Review'
on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
      - reopened


jobs:
  secret-scanning-review:
    runs-on: ARM64
    permissions:
      id-token: write
      contents: read
      security-events: read
    steps:
      - name: 'Secret Scanning Review Action'
        uses: wontonst/secret-scanning-review-action@generic_requests
        with:
          token: ${{ secrets.TMP_RZHENG_PAT }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: true
          runtime: 'python' # or 'python'
