on:
  pull_request:
      types:
      - edited
      - opened
      - synchronize
      - reopened
  
jobs:
  tf-test-cache:
    runs-on: [ARM64]
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Terraform build cache
      uses: ./.github/actions/tf-cache-providers
      with:
        ssh-private-key: ${{secrets.SHARED_INFRA_DEPLOY_KEY}}
        tf-version: 1.3.0
        tfe-token: ${{secrets.TFE_TOKEN}}