on:
  pull_request:
      branches:
        - "heathj/cache-providers"
      types:
      - edited
      - opened
      - synchronize
      - reopened
  
jobs:
  tf-test-cache:
    runs-on: [ARM64,self-hosted,Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Terraform plan
      uses: ./.github/actions/tf-cache-providers
      with:
        ssh-private-key: ${{secrets.SHARED_INFRA_DEPLOY_KEY}}
        tf-version: 1.3.0
        tfe-token: ${{secrets.TFE_TOKEN}}